version: '3'
services:
  db:
    image: 'mongo'
    container_name: mongoDB

  ebay-ads:
    container_name: app
    depends_on:
      - db
    build:
      dockerfile: .
      context: .
    restart: on-failure
    network_mode: service:db
    ports:
      - '8080:8080'
